### ISSUE TITLE
Multiple python files 

### ISSUE THREAD

**Issue by yamifm** [NTNU-IHB/PythonFMU#104]
Hi 
How can I creat a single FMU for multiple python scripts? 
I have a project that have multiple classes in different python file and one main script to execute them.

**Comment by markaren** [comment]
This is certainly possible. Let me find an example.

**Comment by markaren** [comment]
To be more clear, `project_files` is a positional argument. So any input argument after the switches are considered project files.

```
usage: pythonfmu build [-h] -f SCRIPT_FILE [-d DEST] [--doc DOCUMENTATION_FOLDER] [--no-external-tool]
                       [--no-variable-step] [--interpolate-inputs] [--only-one-per-process] [--handle-state]
                       [--serialize-state] [--use-memory-management]
                       [Project files [Project files ...]]

Build an FMU from a Python script.

positional arguments:
  Project files         Additional project files required by the Python script.
```

**Comment by yamifm** [comment]
Thank you very much

**Comment by markaren** [comment]
Closing this issue. Please re-open if there should be any issues with this.
