### ISSUE TITLE
Using explicit unsteady time

### ISSUE THREAD

**Issue by yamifm** [NTNU-IHB/PythonFMU#105]
How can I use explicit unsteady time in code?

**Comment by markaren** [comment]
Can you elaborate?

**Comment by yamifm** [comment]
I am not sure if I need to use the do step in order to use the fmu or can I use a for loop instead. 
I have a 1-d code that I want to use with fmu but the code is an explicit unsteady calculation. 
So I am asking if pythonFMU can let use something different with the fmi2slave

**Comment by markaren** [comment]
I'm really not sure what you mean. An FMU must make use of the doStep call. Otherwise why use FMI? No importing tool would be able to run the FMU as they would expect the FMU to update its state after each call do doStep..

**Comment by yamifm** [comment]
No it is a co-stimulation but in my code I use a for loop with a specific step size and time. The co-sim will have its own step size and time. 
If I understand the do step correctly, the current time and step size will be equal to the co-sim if I am not mistaken. Is my understanding correct?

**Comment by markaren** [comment]
`current_time` and `step_size` is passed from the environment, yes. So the co-simulation environment will expect that you have stepped your model so your internal time = current_time + step_size when you return from the function.

**Comment by markaren** [comment]
Closing this. I reckon this issue is more related to the internals of a slave implementation (not particular to PythonFMU).
