### ISSUE TITLE
Error in load_fmu function

### ISSUE THREAD

**Issue by bressanmarcos** [NTNU-IHB/PythonFMU#106]
Hi, when loading an example from examples folder, I'm getting the following error.

```bash
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyfmi import load_fmu
>>> 
>>> model = load_fmu('Resistor.fmu')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pyfmi/fmi.pyx", line 8342, in pyfmi.fmi.load_fmu
  File "src/pyfmi/fmi.pyx", line 6701, in pyfmi.fmi.FMUModelCS2.__init__
  File "src/pyfmi/fmi.pyx", line 3930, in pyfmi.fmi.FMUModelBase2.__init__
pyfmi.fmi.FMUException: Error loading the binary. The FMU contains no binary for this platform.
```

Do you have any idea of what it could be?

**Comment by markaren** [comment]
When developing locally, you need to build the native libraries yourself. They are not checked into git.
Standard CMake build of pythonfmu/pythonfmu-export. It will put the natives at the correct location.

**Comment by markaren** [comment]
Install pythonfmu through pip to solve this. Mac, however, is not supported. However, you are free to try to build those binaries yourself, but no support will be offered.

**Comment by bressanmarcos** [comment]
> Install pythonfmu through pip to solve this. Mac, however, is not supported. However, you are free to try to build those binaries yourself, but no support will be offered.

It worked perfectly, thank you very much, @markaren !
