### ISSUE TITLE
Error loading FMU file using MATLAB simulink due to library error 

### ISSUE THREAD

**Issue by davidel27** [NTNU-IHB/PythonFMU#110]
Hello I have some issues with loading the fmu file that generated using PythonFMU to MATLAB simulink FMU import module.
The model in matlab is the same model as the given example, just instead of using pyFMI I use matlab simulink.
It recognises the model, the inputs and outputs of the FMU file, but when I try to simulate it, it results with the following error:

Error in supplied FMU: Unable to load dynamic library
'C:\Users\david\Documents\FMU\slrprj\_fmu\c9a9319\PythonSlave\binaries\win64\PythonSlave.dll': The specified module could not be found. 
For more information, see the FMU troubleshooting documentation.

I checked for the following dll and it is do exist and it seems to be correct.
Is there a way to fix that?
Thank you and best regards

**Comment by markaren** [comment]
> The specified module could not be found.

This error could mean that `PythonSlave.dll` itself is missing some dependency. The first thing I would check is whether or not Python is on PATH. PythonFMU requires Python3 on the system (and added to PATH).

You can also use Dependeny Walker to see what dlls the FMU requires (plain PythonFMU requires Python3.dll only)

**Comment by davidel27** [comment]
Hi thank you for your fast replay.
You were right, python was not added to my path.
I use anaconda thefore I added to path the following directorys:
../Anaconda3
../Anaconda3/Scripts
In the first directory there is python.exe and python3.dll.
I managed to launch python and build the fmu directly through the cmd.
(i.e.
python
pythonfmu build -f)
Now it is no longer shows the initial error but just kills the MATLAB and simulink with no reason given.

**Comment by markaren** [comment]
How about other importing tools?  It is quick to check with FMPy using `python -m fmpy.gui`

**Comment by davidel27** [comment]
It is still not working.

I opened a new folder in C:\test
and created python file with the name FMUtest.py:

![image](https://user-images.githubusercontent.com/75980668/102199908-ddc72b00-3ecc-11eb-8a29-c5ca2c7ccc96.png)

Later I opened the CMD as an admini:
and wrote the following commands:

![image](https://user-images.githubusercontent.com/75980668/102200477-8ecdc580-3ecd-11eb-9eb3-c3b4c6f61cda.png)

And the FMU file were created:

![image](https://user-images.githubusercontent.com/75980668/102200589-b4f36580-3ecd-11eb-9ca4-80b11f34bc44.png)

Using FMPy the following error occures:

![image](https://user-images.githubusercontent.com/75980668/102201113-567ab700-3ece-11eb-9300-9190ba641293.png)

Same error for the FMPy GUI when trying to load the FMU.


Using MATLAB simulink, it  does recognise the FMU and the outputs:

![image](https://user-images.githubusercontent.com/75980668/102201658-15cf6d80-3ecf-11eb-9478-0b1b9eced71f.png)

but when trying to run simulation, it crashes with the following error:

![image](https://user-images.githubusercontent.com/75980668/102202006-82e30300-3ecf-11eb-8f67-8eb522231f86.png)
![image](https://user-images.githubusercontent.com/75980668/102202064-91c9b580-3ecf-11eb-9fa2-00951c34157e.png)

I also tried to use RecurDyn as master but it also crushed without giving an error.

**Comment by markaren** [comment]
Can you share the FMU you have?

**Comment by markaren** [comment]
You are using Python 64 bit right?

**Comment by davidel27** [comment]
Yes I have python 64 and the FMU file:

[FMUtest.zip](https://github.com/NTNU-IHB/PythonFMU/files/5695261/FMUtest.zip)

**Comment by markaren** [comment]
![image](https://user-images.githubusercontent.com/6005031/102206381-cb4cf180-3ecc-11eb-94fc-acfc8f20ae1a.png)

I'm running Python 3.7. So I guess I the Python 3.9 API have some new functions. Nevertheless, the FMU loads and provides an error. Could it be your Python version? Perhaps Python 3.9 is just incompatible with PythonFMU. I think 3.8 is the highest we have tested.

**Comment by davidel27** [comment]
I use python 3.8.3

**Comment by davidel27** [comment]
I will try python 3.7 and let you know.
thank you very much!

**Comment by markaren** [comment]
Seems Python 3.9 is also ok: https://github.com/NTNU-IHB/PythonFMU/pull/111

**Comment by davidel27** [comment]
Can you give me the environment that you use?
Is there additional stuff I need to install except python, PythonFMU? (with no external packges)

**Comment by markaren** [comment]
I'm using plain Python 3.7. `pip install pythonfmu` is enough if you only use core Python libraries.
However, the CI is running with versions ranging from 3.6 to 3.8.

Btw, I looked at the time API and there is no function called `pause`. So that would lead to a crash. Also, perhaps MATLAB/SIMULink do not like the `needsExecutionTool` attribute in the `modelDescription.xml` ? Try re-exporting with `--no-external-tool`

**Comment by markaren** [comment]
Also the error you get from fmpy does not seem to be related to PythonFMU (etree). Does it work with other FMUs?

**Comment by davidel27** [comment]
I created a new environment in anaconda named py374 and have a python version 3.7.4.
I installed the libraries:
pythonfmu
FMPy

I changed a little bit the code:
![image](https://user-images.githubusercontent.com/75980668/102218342-7cac5100-3ee6-11eb-854f-9303ae1326e4.png)

and build using the command:
pythonfmu build -f FMUtest.py --no-external-tool

Using FMPy GUI it succeed!!:
![image](https://user-images.githubusercontent.com/75980668/102218579-db71ca80-3ee6-11eb-875b-a89b7150893e.png)

But Using MATLAB simulink it resulted with the same error as before:
![image](https://user-images.githubusercontent.com/75980668/102218664-fba18980-3ee6-11eb-9ea3-9bd2f171e3a9.png)

I will try to contact MathWork support to obtain the solution.

The files in the folder:
[FMUtest.zip](https://github.com/NTNU-IHB/PythonFMU/files/5696035/FMUtest.zip)


Best regards and Thank you very much!!

**Comment by markaren** [comment]
Closing. Please re-open if you find that PythonFMU has an issue that keeps it from working with MATLAB/Simulink.

**Comment by MinsGoing** [comment]
I had the same problem, did you solve it?

**Comment by davidel27** [comment]
> I had the same problem, did you solve it?

Yes I have managed to solve it. 

Can you explicitly say which software you used as master? And which python environment do you have? (is it anaconda?) And also the operating system. 
The solution may be a little bit diffrent in each scenario.

**Comment by MinsGoing** [comment]
I'm using **Anaconda** environment `(D:\Anaconda3\envs\fmi_env)` on win11 to execute `pythonfmu build -f `.I added  `(D:\Anaconda3\envs\fmi_env)` to the system path. Everything works fine in FMPy GUI, on the same machine, import to simulink `(matlab 2020R)` without `scope` connected, click to run without crashing, connect to `scope` to run and it crashes.

**Comment by MinsGoing** [comment]
> > I had the same problem, did you solve it?
> 
> Yes I have managed to solve it.
> 
> Can you explicitly say which software you used as master? And which python environment do you have? (is it anaconda?) And also the operating system. The solution may be a little bit diffrent in each scenario.

I'm using **Anaconda** environment` (D:\Anaconda3\envs\fmi_env)` on win11 to execute `pythonfmu build -f` .I added `(D:\Anaconda3\envs\fmi_env)` to the system path. Everything works fine in FMPy GUI, on the same machine, import to simulink `(matlab 2020R)` without `scope `connected, click to run without crashing, connect to `scope `to run and it crashes.

**Comment by davidel27** [comment]
> > > I had the same problem, did you solve it?
> > 
> > 
> > Yes I have managed to solve it.
> > Can you explicitly say which software you used as master? And which python environment do you have? (is it anaconda?) And also the operating system. The solution may be a little bit diffrent in each scenario.
> 
> I'm using **Anaconda** environment` (D:\Anaconda3\envs\fmi_env)` on win11 to execute `pythonfmu build -f` .I added `(D:\Anaconda3\envs\fmi_env)` to the system path. Everything works fine in FMPy GUI, on the same machine, import to simulink `(matlab 2020R)` without `scope `connected, click to run without crashing, connect to `scope `to run and it crashes.

The main issue is the usage of anaconda. In anaconda environment under windows, the environment variables are not properly defined. Although, manually adding the environment variables in the system PATH. 

The solution that worked for me is to uninstall the anaconda framework and reinstall anaconda with "Add to PATH envirnment variables..." option checked (although it is not recomended by the anaconda installer).

Make sure to reboot your machine after reinstalling anaconda and that should work.

**Comment by MinsGoing** [comment]
> > > > I had the same problem, did you solve it?
> > > 
> > > 
> > > Yes I have managed to solve it.
> > > Can you explicitly say which software you used as master? And which python environment do you have? (is it anaconda?) And also the operating system. The solution may be a little bit diffrent in each scenario.
> > 
> > 
> > I'm using **Anaconda** environment` (D:\Anaconda3\envs\fmi_env)` on win11 to execute `pythonfmu build -f` .I added `(D:\Anaconda3\envs\fmi_env)` to the system path. Everything works fine in FMPy GUI, on the same machine, import to simulink `(matlab 2020R)` without `scope `connected, click to run without crashing, connect to `scope `to run and it crashes.
> 
> The main issue is the usage of anaconda. In anaconda environment under windows, the environment variables are not properly defined. Although, manually adding the environment variables in the system PATH.
> 
> The solution that worked for me is to uninstall the anaconda framework and reinstall anaconda with "Add to PATH envirnment variables..." option checked (although it is not recomended by the anaconda installer).
> 
> Make sure to reboot your machine after reinstalling anaconda and that should work.

Thank you very much, now that it's working
