### ISSUE TITLE
Unable to create FMU using compiled module dependency

### ISSUE THREAD

**Issue by svanimisetti** [NTNU-IHB/PythonFMU#114]
I am trying to create an FMU using a test python script which uses a module dependency. If I use the module as a .py file, everything works fine. However, if I compile it to a .pyd file for distribution, I get the following error and an FMU is not generated. Any suggestions on how this can be resolved?

> (pydev36) W:\Sandbox\PY_FMU_Test>pythonfmu build -f test_py_fmu.py modules
> Traceback (most recent call last):
>  File "C:\apps\Anaconda3\envs\pydev36\Scripts\pythonfmu-script.py", line 10, in <module>
>     sys.exit(cli_main())
>   File "C:\apps\Anaconda3\envs\pydev36\lib\site-packages\pythonfmu\__main__.py", line 55, in cli_main
>     execute(**options)
>   File "C:\apps\Anaconda3\envs\pydev36\lib\site-packages\pythonfmu\builder.py", line 189, in build_FMU
>     return dest_file
>   File "C:\apps\Anaconda3\envs\pydev36\lib\tempfile.py", line 809, in __exit__
>     self.cleanup()
>   File "C:\apps\Anaconda3\envs\pydev36\lib\tempfile.py", line 813, in cleanup
>     _shutil.rmtree(self.name)
>   File "C:\apps\Anaconda3\envs\pydev36\lib\shutil.py", line 500, in rmtree
>     return _rmtree_unsafe(path, onerror)
>   File "C:\apps\Anaconda3\envs\pydev36\lib\shutil.py", line 390, in _rmtree_unsafe
>     _rmtree_unsafe(fullname, onerror)
>   File "C:\apps\Anaconda3\envs\pydev36\lib\shutil.py", line 395, in _rmtree_unsafe
>     onerror(os.unlink, fullname, sys.exc_info())
>   File "C:\apps\Anaconda3\envs\pydev36\lib\shutil.py", line 393, in _rmtree_unsafe
>     os.unlink(fullname)
> PermissionError: [WinError 5] Access is denied: 'C:\\Users\\<uid>\\AppData\\Local\\Temp\\pythonfmu_mu7i244k\\modules\\my_module.pyd'

**Comment by markaren** [comment]
Sorry for not replying sooner. 
To be honest, I don't know anything about modules. 
Therefore I don't know why the error occurs, or how it can be resolved.

Could you attach a minimal reproduceable example? Perhaps I could look at it sometime. But no promises.
The not so fun alternative is to try and figure out a fix yourself (and hopefully submit a PR!)

**Comment by markaren** [comment]
Is the file compiled to `__pycache__` ? In that case the file is not added to the FMU..

**Comment by svanimisetti** [comment]
Yes - the file does not seem to appear in __pycache__. I will have to dig a little further.

**Comment by markaren** [comment]
I was trying to say that pythonfmu explicitly ignores __pycache__ when building the FMU.

**Comment by markaren** [comment]
Please reopen if further information appears.
