### ISSUE TITLE
Darwin support

### ISSUE THREAD

**Issue by alfoa** [NTNU-IHB/PythonFMU#116]
As follow up to the previous issue (#115).
I was wondering if you are planning to support Darwin (Mac) OS.

**Comment by markaren** [comment]
I difficulties supporting an OS I have/will never use unfortunately. 
It is however possible to build the shared library manually, but I can't guarantee the the native code is compliant with the compiler used by MacOS.

**Comment by alfoa** [comment]
@markaren  Sorry if I bother you again. Do you have a doc or something that explains how to build manually? or can you just list here what needs to be done?

**Comment by markaren** [comment]
What I assume you have to is:

1) cd to `pythonfmu/pythonfmu-export` and run something akin to what you'd do on linux:
```
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
```
2) run pip install . from the root directory.

You should now have a pythonfmu installation that supports darwin, but only darwin.
What you could do to support all platforms is to not perform step 2), but simply copy the .dylib you generated in 1) from `resources/binaries/darwin` into the FMU you have. The .dylib file can be re-used for all your FMUs.

**Comment by joshua-cogliati-inl** [comment]
For what it is worth, in order to compile it with Darwin, we had to change:
```
target_link_libraries(pythonfmu-export
        PRIVATE
        ${Python3_LIBRARIES}
        )
```
to 
```
target_link_libraries(pythonfmu-export
        PRIVATE
        Python3::Module
        )
```

**Comment by joshua-cogliati-inl** [comment]
In order to support darwin, change:
```
target_link_libraries(pythonfmu-export
        PRIVATE
        ${Python3_LIBRARIES}
        )
```
to:
```
if (WIN32)
  target_link_libraries(pythonfmu-export
        PRIVATE
        ${Python3_LIBRARIES}
        )
else ()
  target_link_libraries(pythonfmu-export
        PRIVATE
        Python3::Module
        )
endif ()
```
in PythonFMU/pythonfmu/pythonfmu-export/src/CMakeLists.txt
Note using Python3::Module works in Linux as well.

**Comment by jschueller** [comment]
it should work now with #187

**Comment by sergiochavezlazo96** [comment]
Hello! could you please tell me how to compile to Darwin given that the solution is already implemented? By default (example in README) I am only getting the binaries for linux and windows. Thank you!

**Comment by markaren** [comment]
You basically need to build the native code from source. I.e build the C++ project located in python-fmu export using CMake. A sucessfull build should yield a resources/darwin/somefile.dylib that needs to be copied into the FMU.

**Comment by jschueller** [comment]
you could also try osx binaries from conda-forge distribution
