### ISSUE TITLE
extracting values each time step in do_step

### ISSUE THREAD

**Issue by yamifm0f** [NTNU-IHB/PythonFMU#122]
how can I extract the loop values for each time step using do_step?

as I understand it to extract all the values in a loop the csv should be outside of the loop 

like this
`
with open('sample.csv', 'w') as csvFile:
   fieldnames = ['Num' ,'temp' ,'kit']
   writer = csv.DictWriter(csvFile, fieldnames=fieldnames,delimiter=',', quotechar='"',)
   writer.writeheader()
   # Timestep loop
   t = np.zeros((numSteps))
   for n in range(numSteps):

      add = 200
      temp = add +1
      kit = 30+n 
      
      writer.writerow({'Num': n ,'temp': temp ,'kit':  kit  `})
`

and the above works fine

when I try it with the fmu class 
`
with open('FMU_Results.csv', 'w') as csvFile:
   fieldnames = ['Time' ,'Results']
   writer = csv.DictWriter(csvFile, fieldnames=fieldnames,delimiter=',', quotechar='"')
   writer.writeheader()

   # Timestep loop
   class Python(Fmi2Slave):
      author = ""
      description = ""
      def __init__(self, **kwargs):
         super().__init__(**kwargs)

      def do_step(self, current_time, step_size):
         add = step_size +1
         results = add + add
         writer.writerow({'Time': current_time,'Results':results})
         return True
`

I can only get the last time step values with having the csv writing inside the do_step method. the above are just examples to clarify what I mean but they are not complete scripts and will not run.

**Comment by yamifm0f** [comment]
I apologise for the way the codes look but it dose not want to be corrected for some reason.

**Comment by markaren** [comment]
This sounds like a pure Python issue. I don't understand the issue or how it is related specifically to pythonfmu.

**Comment by yamifm0f** [comment]
No. I do understand that this might not be an fmu issue. but the steps I took to write the csv file are python correct and when applied to pythonfmu it did not work because fmu could not be initiated (if I put the Fmi2Slave and do_step inside the csv with open).

**Comment by yamifm0f** [comment]
I noticed that there is a csv builder in pythonfmu so I am wondering if that would help in extracting the values for each do_step time step.

**Comment by markaren** [comment]
The normal way to do this would be to simulate the FMU in an external tool.

**Comment by markaren** [comment]
> I noticed that there is a csv builder in pythonfmu so I am wondering if that would help in extracting the values for each do_step time step. I do not see any example so I am not sure how it works thought

The CSV Builder is for exporting CSV files to FMUs, not creating CSV files while simulating, which I think is what you want to do?
There is no reason it should not be possible to export csv using pythonfmu as you can execute arbitrary code, but you need to consider scope etc. If I did it, I would make the output path a parameter and create the csv file during exitInitialisationMode. The csv writer would be a field of the class and would not be instantiated before simulation. Putting it in constructor or global scope would mean that the code is executed twice (during creation of FMU and during simulation)

**Comment by yamifm0f** [comment]
I created a class to extract the values each step. It made it a bit slow but at least I get the values I need. the master program unfortunately will not give me the array values only single values.

**Comment by markaren** [comment]
I still don't understand what you are trying to do. If you are exporting the internal state of the FMU as part of the logic of the FMU itself you can just access the python variables like any other python code. If you are doing it from the outside, then it is not related to pythonfmu.

**Comment by yamifm0f** [comment]
I am trying to extract my code results from fmu each time step. The results are arrays. Usually in a python code I just need to write the extracting csv outside of the loop and that works fine. In pythonfmu's case I can not do that, however, I can get the last value when the loop finish. If I do the usual way with csv and fmu(ie. putting pythonfmu inside the with csv) the master program will not be able to read the fmu slave class (that is what happened to me).
