### ISSUE TITLE
Problem with initialization of output

### ISSUE THREAD

**Issue by kosmylo** [NTNU-IHB/PythonFMU#133]
According to the example in the `demo.ipynb`, the variables have to be initialized in the `__init__` including also values for the outputs. What should I do if I do not know the initial value for an output? I am getting results that they have wrong values for the first time step. In the following plot, I have initialized all outputs to 1.

![test](https://user-images.githubusercontent.com/13433764/128912503-9f15e456-6bf8-4b66-bce0-6c43631268d7.PNG)

**Comment by markaren** [comment]
You can override enter and exit initialization model if that helps.

**Comment by kosmylo** [comment]
It is not clear with what to override them. Let's say in the following example:

```
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.intIn = 1
        self.realOut = 3.0
        self.register_variable(Integer("intOut", causality=Fmi2Causality.input))
        self.register_variable(Real("realOut", causality=Fmi2Causality.output))
```
If I do not want to initialize the values _self.intIn_ and _self.realOut_ what should I do? What I have tried is to not include them at all in the `__init__`, but I am getting an error.

**Comment by markaren** [comment]
If you want lazy initialization you could provide `register_variable` with getter and setter lambdas (you only need to provide a getter for an output) rather than referencing fields. The best documentation you'll get is to understand the `Fmi2Slave` class itself.

**Comment by kosmylo** [comment]
Unfortunately, it is a bit difficult for me to completely understand the `Fmi2Slave`. I tried to remove the initialization for inputs and outputs and include setter and getter as follows:

```
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.register_variable(Integer("intOut", causality=Fmi2Causality.input, setter=lambda: self.intIn))
        self.register_variable(Real("realOut", causality=Fmi2Causality.output, getter=lambda: self.realOut)
```
But the FMU cannot be exported, since I am getting an AttributeError.

As I mentioned in my first post, if I use initialization, I am getting the correct results, but shifted one timestep, because in the first timestep it uses the values that I have used as initialization (which are random). In the first step, I cannot know what the values for the inputs and outputs are, since the inputs are coming from another file and the outputs should be accessible after the first step of the simulation has been completed.

**Comment by markaren** [comment]
```
self.register_variable(Integer("intOut", causality=Fmi2Causality.input, setter=lambda: self.intIn))
self.register_variable(Real("realOut", causality=Fmi2Causality.output, getter=lambda: self.realOut)
```

Two issues with this code. 
1 )  `self.intIn` and `self.realOut` has not been declared.
2)  lambda a) setter takes and argument and b) Python does not allow assignments directly in lambdas, so you need to pass a function reference.

> because in the first timestep it uses the values that I have used as initialization

Then override `exitInitializationMode`. Per the standard, external values ha been assigned by this point.

**Comment by kosmylo** [comment]
I did what you suggested with the `exitInitializationMode` and it works fine in the simple setup that I simulate the FMU with the inputs coming from CSV files. The result that I am getting is the following:

![test](https://user-images.githubusercontent.com/13433764/130059121-893e8852-a409-49a8-afea-2aa0d9877027.PNG)

We can see that the initial values are correct.

However, when I am trying to simulate it with other FMUs as inputs (instead of the CSV files) I am getting the following error:

```
Traceback (most recent call last):

  File "C:\Users\kosmy\FMU unification\run_master_pyfmi.py", line 28, in <module>
    res = master_simulator.simulate(final_time = 96, options = opts)

  File "src\pyfmi\master.pyx", line 1479, in pyfmi.master.Master.simulate

  File "src\pyfmi\master.pyx", line 1180, in pyfmi.master.Master.initialize

  File "src\pyfmi\master.pyx", line 123, in pyfmi.master.exit_initialization_mode

  File "src\pyfmi\fmi.pyx", line 4689, in pyfmi.fmi.FMUModelBase2.exit_initialization_mode

FMUException: Exit Initialize returned with an error. Enable logging for more information, (load_fmu(..., log_level=4)).
```

Do you have any idea of why is this happening?

**Comment by markaren** [comment]
> Do you have any idea of why is this happening?

I don't know. Could be an issue in pythonfmu, pyfmi, user code, runtime environment or a combination.
