### ISSUE TITLE
Run PythonFMU from another folder

### ISSUE THREAD

**Issue by kosmylo** [NTNU-IHB/PythonFMU#134]
I have installed `pythonfmu` through `pip install pythnonfmu`, but I want also to have another folder of pythonfmu to be able to make some changes in the different functions without having to modify the main one. Is there a command that I can add to the `pythonfmu build` to let it know that I want to run it from another path?

**Comment by markaren** [comment]
Simply provide the full path of the (modified) executable?

**Comment by kosmylo** [comment]
What I am currently doing is that I have the `pythonfmu` folder and I change the `fmi2slave` inside this folder. Before executing the command `pythonfmu build -f test.py` I am doing `cd` to the location that I have the modified `pythonfmu` folder. But it does not take into account the modifications.

**Comment by markaren** [comment]
I'd just switch between `pip install .` (local changes) and `pip install pythonfmu` (upstream). Alternatively run `__main__.py` explicitly.

I'm opting to close this issue as it is not really specific to pythonfmu.

**Comment by kosmylo** [comment]
Yes, I understand. Thanks for the help.
