### ISSUE TITLE
No file named "pythonfmu-builder.jar"

### ISSUE THREAD

**Issue by Bigstrong-hust** [NTNU-IHB/PythonFMU#14]
Hi markaren, thank you for your contribution to this project. I have downloaded the source code and followed the README file, but I found that there is no file named "pythonfmu-build.jar". Any advices?
Thanks

**Comment by markaren** [comment]
`pythonfmu-build.jar` is not checked into git. The idea is that you build it from source, or download it from the latest GitHub CI run. Click on the latest build here: https://github.com/NTNU-IHB/PythonFMU/actions

The jar is available as artifact in the upper left corner. 

![image](https://user-images.githubusercontent.com/6005031/72330706-443d3b00-36b7-11ea-962e-45e23157a484.png)

**Comment by markaren** [comment]
You are not the first one to find this confusing.

**Comment by Bigstrong-hust** [comment]
Thanks for immediate response, and the artifact is in the upper right conner.
