### ISSUE TITLE
Packing problem

### ISSUE THREAD

**Issue by zhangbin006** [NTNU-IHB/PythonFMU#144]
Hello, can you package the neural network into FMU

**Comment by markaren** [comment]
You can package any Python code, however the FMU does not package dependencies. If you run the FMU on another PC, the same libraries that you use needs to be pre-installed. There is also an issue on linux, where you'll need to rebuild the shared library to link to the Python version used if it is not 3.9.

**Comment by zhangbin006** [comment]
Hi, do you have a tutorial on packaging

**Comment by zhangbin006** [comment]
I see. thank you

**Comment by zhangbin006** [comment]
Hi,Do you have any examples of this

**Comment by markaren** [comment]
Examples of what? The README, tests and examples provides examples and hints.

**Comment by zhangbin006** [comment]
This is an example of a neural network compiled into fMU format

**Comment by markaren** [comment]
IMO, there is nothing special about a neural network. It's Python code. So, no I don't have an example.

**Comment by zhangbin006** [comment]
Oh, oh, okay. Thank you
