### ISSUE TITLE
do_step(self, current_time, step_size)

### ISSUE THREAD

**Issue by zhangbin006** [NTNU-IHB/PythonFMU#146]
Hello, what does step_size mean? The do_step function is executed only once. My problem is that I wrote multiple if... Elif statement, but every time it does the first if statement, the next one is not doing the judgment, I don't know if I made it clear.

**Comment by markaren** [comment]
> Hello, what does step_size mean?

I assume you are familiar with the FMI specification? `step_size` is the delta time your model should compute.

> do_step function is executed only once

Sounds like an issue with your code.

Please only use the issue tracker for bugs in the software.
