### ISSUE TITLE
How do I set the variables of the pre-accepted model file

### ISSUE THREAD

**Issue by 2018-Summer** [NTNU-IHB/PythonFMU#147]
Hello, I would like to ask a question, when I pack an FMU, how to set a variable or other things in advance, accept the model file sent by others, so as to make my FMU file run.

**Comment by markaren** [comment]
I don't understand your question.

**Comment by 2018-Summer** [comment]
Fmu packaging, how to pre-define the parameters or variables that accept a binary file.

**Comment by markaren** [comment]
Load the file from resources that are bundled in the FMU (no user interaction, file is bundled with the FMU) or let the user provide a string parameter that represents the file to load.
