### ISSUE TITLE
Not passing FMUChecker: Could not load the DLL: The specified module could not be found

### ISSUE THREAD

**Issue by t3x4y** [NTNU-IHB/PythonFMU#150]
Hi,
I am getting the following issue in FMUChecker 64-bit. The FMU itself just adds two values and there are no dependencies. It's probably something trivial, but I really would appreciate a pointer as to what causes the problem.

Thanks!

[INFO][FMUCHK] FMI compliance checker 2.0.4 [FMILibrary: 2.0.3] build date: Nov 6 2017
[INFO][FMUCHK] Called with following options:
[INFO][FMUCHK] fmuCheck.win64 add2.fmu
[INFO][FMUCHK] Will process FMU add2.fmu
[INFO][FMILIB] XML specifies FMI standard version 2.0
[INFO][FMUCHK] Model name: Add2
[INFO][FMUCHK] Model GUID: 5abe265f-9a2e-11ec-a8d0-98e743adedce
[INFO][FMUCHK] Model version:
[INFO][FMUCHK] FMU kind: CoSimulation
[INFO][FMUCHK] The FMU contains:
0 constants
0 parameters
0 discrete variables
4 continuous variables
2 inputs
1 outputs
1 local variables
0 independent variables
0 calculated parameters
4 real variables
0 integer variables
0 enumeration variables
0 boolean variables
0 string variables

[INFO][FMUCHK] No input data provided. In case of simulation initial values from FMU will be used.
[INFO][FMUCHK] Printing output file header
"time","out"
[INFO][FMUCHK] Model identifier for CoSimulation: Add2
[INFO][FMILIB] Loading 'win64' binary with 'default' platform types
**[FATAL][FMICAPI] Could not load the DLL: The specified module could not be found.

[FATAL][FMUCHK] Could not create the DLL loading mechanism(C-API) for CoSimulation.**
FMU check summary:
FMU reported:
0 warning(s) and error(s)
Checker reported:
0 Warning(s)
2 Error(s)
2 Fatal error(s) occurred during processing

**Comment by markaren** [comment]
Are you using 32-bit Python? PythonFMU supports only 64-bit of the box. Python on PATH?

**Comment by t3x4y** [comment]
It was PATH, due to us using Anaconda. Everything's working great now, thanks a lot!
