### ISSUE TITLE
There was an issue running the build_unix.sh script

### ISSUE THREAD

**Issue by 2018-Summer** [NTNU-IHB/PythonFMU#153]
CMake Error at CMakeLists.txt:37 (add_compile_definitions):
  Unknown CMake command "add_compile_definitions".
How to set Py_LIMITED_API for Python 3.6.5,
How do I set add_compile_definitions(Py_LIMITED_API) for sh

**Comment by markaren** [comment]
`add_compile_definitions` was added in CMake 3.12. I assume you use an outdated version.

**Comment by 2018-Summer** [comment]
I am currently testing fmu on Linux, but still reporting the error in the picture, I am just recompiling a Linux binary, I am using python3.6.5, I don't know what is going on. Please help me to guide me how to do next.
![error](https://user-images.githubusercontent.com/35995146/165250420-cdd3c1fc-18a5-4169-b0ef-8b8a3dc8878f.png)

**Comment by 2018-Summer** [comment]
Hello, I would like to ask how to check fMU compliance in Linux

**Comment by markaren** [comment]
> Hello, I would like to ask how to check fMU compliance in Linux
https://github.com/modelica-tools/FMUComplianceChecker

>  I am just recompiling a Linux binary, I am using python3.6.5, I don't know what is going on
Are you sure you are using the correct binary in the FMU? The one that comes with pip/conda requires Python 3.9 on linux.

**Comment by 2018-Summer** [comment]
It should be true that fMU is passed using FMPy on Linux.

**Comment by 2018-Summer** [comment]
I have recompiled the so file for 3.6.5 (python 3.6.5 is installed on Linux), but it still fails
