### ISSUE TITLE
FMUException with PyFMI

### ISSUE THREAD

**Issue by Antoine-C-Hubert** [NTNU-IHB/PythonFMU#155]
Hello guys,

I try to load an FMU created with pythonfmu using pyfmi.load_fmu function.
I get this error :
**FMUException: Models that need an execution tool are not supported**

Are there some options to enable the connection between both libraries ?

Example script :

dummyFmu.py 

    from pythonfmu import Fmi2Causality, Fmi2Variability, Fmi2Slave, Real
    
    class Dummy(Fmi2Slave):
        author = "YourHumbleServant"
        description = "Dummy FMU to be loaded with PyFMI"
    
        def __init__(self, **kwargs):
            super().__init__(**kwargs)
    
            # Input variables
            self.in_x = 0.0
            # Output variables
            self.out_x = 0.0
    
            
            # Register FMU variables
            # Inputs
            self.register_variable(Real("in_x", causality=Fmi2Causality.input, variability=Fmi2Variability.continuous))
            # Outputs
            self.register_variable(Real("out_x", causality=Fmi2Causality.output, variability=Fmi2Variability.continuous))
            
    
        def do_step(self, current_time, step_size):
            """Main function to apply one time step.
    
            Args:
                current_time (float): current simulation time in the scheduler.
                step_size (float): size of the time step in the scheduler.
            """
            self.out_x = self.in_x + 1
            return True

The FMU is build with 

`pythonfmu build -f dummyFmu.py`

And loaded with

    import pyfmi
    pyfmi.load_fmu("Dummy.fmu")

pyfmi version 2.9.7
pythonfmu version 0.6.2

Thanks a lot!

**Comment by markaren** [comment]
You can manually edit the `modelDescription.xml` or re-export with `--no-external-tool`

**Comment by Antoine-C-Hubert** [comment]
It works for standalone FMU but also for my cosimulation built with fmpy library.
Thanks a lot !
