### ISSUE TITLE
String output not working 

### ISSUE THREAD

**Issue by Poulami-Sarkar** [NTNU-IHB/PythonFMU#156]
Hi,
I am trying to create an FMU that produces a String output. However, i am getting  a blank result when the output is of type String.
This issue doesn't happen for other types. 

Here is my code:
# FMU CODE
```
from pythonfmu import Fmi2Causality, Fmi2Variability, Fmi2Slave, Real,String

class Resistor(Fmi2Slave):

    author = "John Doe"
    description = "A simple description"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.test = 20.

        self.register_variable(String("test", causality=Fmi2Causality.output))


    def do_step(self, current_time, step_size):

        self.test = "sdfsdf"
        return True
````

# Code for using the FMU
```
from fmpy import *
fmu ="Resistor.fmu"
endTime = 1.0
stepSize = 1.0
res = simulate_fmu(fmu,stop_time=endTime,output_interval=stepSize)
res
```

# Output (The string value  is not being displayed here)
```
SimulationResult([(0.,), (1.,)], dtype=[('time', '<f8')])
```

Could you please help me with this issue?

**Comment by markaren** [comment]
There is no way for pythonfmu to read the __temporary__ variable `"test"`. Try:

```python
self.str = "test"
self.register_variable(String(self.str, causality=Fmi2Causality.output))
```

**Comment by markaren** [comment]
Oh, I read your code wrong. Anyway, you instantitate `test` as an integer, then declare it as an String. I'm surprised the application does not crash.

**Comment by Poulami-Sarkar** [comment]
I have changed test to string and I am still getting the same issue:

```
class Resistor(Fmi2Slave):

    author = "John Doe"
    description = "A simple description"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.test = "20"

        self.register_variable(String("test", causality=Fmi2Causality.output))


    def do_step(self, current_time, step_size):

        self.test = "sdfsdf"
        return True
```

I am building the  fmu using the following command: 
```
pythonfmu build -f .\test.py
```

**Comment by markaren** [comment]
Try getting the value directly using the API. I suspect the function call you are using in the importer only supports numbers.

**Comment by Poulami-Sarkar** [comment]
Could you please let me know how to do that?

**Comment by markaren** [comment]
Using the fmpy API. Its not related to pythonfmu.
