### ISSUE TITLE
Wish: Support of Modelica 4.0

### ISSUE THREAD

**Issue by bertrandhaut** [NTNU-IHB/PythonFMU#161]
Dear,

I've tried to use a FMU generated by PythonFMU inside the Wolfram System Modeler tool.
It worked when the version 3.2.3 of Modelica library was used.

It fails when the version 4.0 of Modelica is used. Error message is 

Error: PythonSlave_fmu [[66:3-66:3]] Class not found. When looking up **Modelica.SIunits.Time** in scope PythonSlave_fmu, SIunits was not found in Modelica.

A quick look showed that, in Modelica 4.0, the units are now in **Modelica.Units.SI.Time**. 

It would be nice to have also a support of Modelica 4.0.

**Comment by markaren** [comment]
I don't quite see how this issue can be related to PythonFMU as the package has no connection with Modelica in any way shape or form.
