### ISSUE TITLE
No demo for using machine learning in an FMU

### ISSUE THREAD

**Issue by msteinsto** [NTNU-IHB/PythonFMU#165]
"Can I use PythonFMU to run machine learning models?" seems to be a frequently asked question. I think having an additional demo wrapping a basic exported machine learning model in an FMU could be of benefit to the community

**Comment by msteinsto** [comment]
I have created a demo for wrapping a TensorFlow sin approximation ML model as an FMU, however I do not have sufficient access rights to create a new branch and submit at PR in this repo

**Comment by ClaasRostock** [comment]
Agree :-)
