### ISSUE TITLE
Identical GUIDs when creating FMUs at the same time

### ISSUE THREAD

**Issue by mb-tt** [NTNU-IHB/PythonFMU#166]
I would like to ask why the GUID of an FMU is set as class variable [here](https://github.com/NTNU-IHB/PythonFMU/blob/4524b3ea37de7cbe49490d1a0d694cd64e7b3665/pythonfmu/fmi2slave.py#L32)?

My problem is that I want to create multiple FMUs at the same time from different source files and then address them by GUID. At the moment this would create FMUs with the same GUID and create an error because it's "the same" FMU. A workaround for me was to create the GUID in the constructor of `Fmi2Slave`.

The [FMI Spec 2.0.4 P. 20](https://github.com/modelica/fmi-standard/releases/download/v2.0.4/FMI-Specification-2.0.4.pdf) says btw:
> Argument fmuGUID is used to check that the modelDescription.xml file (see section 2.3) is compatible with the C code of the FMU. It is a vendor specific globally unique identifier of the XML file (for example, it is a “fingerprint” of the relevant information stored in the XML file).

**Comment by markaren** [comment]
I guess none of the class vars should be just that.

**Comment by markaren** [comment]
#172 should fix the issue. The uuid is not generated or used according to the standard, but it should fix your issue. A client side fix in the meantime would also be to set the uuid manually prior to generating a new model.

I'm not sure when an update to pip will happen. This project is not a priority for me.

**Comment by mb-tt** [comment]
What was the reason for using `repr(uuid1())` now instead of `str(...)` before?

When I generate an FMU now the model description looks this way: `guid="UUID('400a251f-a78c-11ed-b526-0892040e6c26')"` In my opinion this isn't a valid GUID as defined in the standard.

**Comment by markaren** [comment]
It's a bug then. I'll revert to the old logic.

**Comment by markaren** [comment]
See #174

**Comment by mb-tt** [comment]
Thank you for fixing it so quickly ❤

**Comment by markaren** [comment]
The last "fix" had an ugly mistake. Fixed in #175
