### ISSUE TITLE
[Question] Model Exchange Support?

### ISSUE THREAD

**Issue by charelstoncrabb** [NTNU-IHB/PythonFMU#179]
Are there any plans to provide a model exchange FMU by, for example, splitting the `Fmi2Slave` ABC into CS/ME versions? I appreciate that this is a pretty big lift, and maybe there aren't enough use cases/isn't enough general desire, but for my purposes it could be quite useful.

**Comment by markaren** [comment]
Unfortunately, no plans for such a feature.
