### ISSUE TITLE
Unable to run FMU in Dymola

### ISSUE THREAD

**Issue by sede-fa** [NTNU-IHB/PythonFMU#184]
Hi guys,

First off, really cool project!
I've been able to generate FMUs fine with my python code and have been able to run with FMpy and pyfmi.
However, when I try to use these FMUs in dymola with a simple input block, the model fails to initialise. The error message is also not so helpful here. For this case I mainly used the Resistor model and the example in the readme. 

Any help would be much appreciated.

**Comment by markaren** [comment]
Yeah.. I don't really have a solution unfortunatly. 

Similar issue: https://github.com/NTNU-IHB/PythonFMU/discussions/124

**Comment by sede-fa** [comment]
Sorry I somehow couldn't find this issue. I will close this one.
