### ISSUE TITLE
Publication on pypi on conda-forge

### ISSUE THREAD

**Issue by fcollonval** [NTNU-IHB/PythonFMU#19]
@markaren, thanks for the merge 

I already have account on pypi.org and have started the workflow to publish on [conda-forge](https://github.com/conda-forge/staged-recipes/pull/10726). Is it okay for you if I carry on and add you the right to manage those publication too?

**Comment by markaren** [comment]
I guess so. But I would wait to publish a first version until #16 and #18 have been fixed.

**Comment by fcollonval** [comment]
Could I publish a prerelease version (this means additional option needs to be passed to the package manager to pull the package)? Just to have thing in place (and ease sharing the code with colleagues 😉 ).

**Comment by markaren** [comment]
Sure, go ahead.

**Comment by fcollonval** [comment]
0.3.0a0 released on https://pypi.org/project/pythonfmu/

Unfortunately for conda, I need to compile for macOS too. So I open a PR for that.

**Comment by fcollonval** [comment]
@markaren Can I merge #21 and proceed with a first official publication (v0.3.0) on Pypi.org?

Do you have an account on https://pypi.org/? So I can add you as package owner.

Note: We could set a CD github action to do so at release publication. But you are the only one able to do it as it requires storing secret API key as explained there:
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-python-with-github-actions#publishing-to-package-registries

**Comment by markaren** [comment]
You can merge #21. I just added a pypi account. User is my github registered mail.

**Comment by markaren** [comment]
Any action required by me? My user is actually `laht`. Not the e-mail.

**Comment by fcollonval** [comment]
You should now have owner rights on https://pypi.org/project/pythonfmu/

Regarding conda-forge, I'm waiting for admin to approve the PR:
https://github.com/conda-forge/staged-recipes/pull/10726
