### ISSUE TITLE
How to Declare Additional Sub-functions in pythonfmu Beyond '__init__' and 'do_step'?

### ISSUE THREAD

**Issue by hsd0937** [NTNU-IHB/PythonFMU#205]
When using pythonfmu, I noticed that only __init__ and do_step functions are declared. Is it possible to declare other sub-functions, and if so, how can I do that?

**Comment by markaren** [comment]
See additional functions in fmi2slave.py

**Comment by hsd0937** [comment]
Thank you for the update.
I checked fmi2slave and want to call a custom function. How can I do that?

**Comment by markaren** [comment]
```python
  def setup_experiment(self, start_time: float):
      pass

  def enter_initialization_mode(self):
      pass

  def exit_initialization_mode(self):
      pass

  @abstractmethod
  def do_step(self, current_time: float, step_size: float) -> bool:
      pass

  def terminate(self):
      pass
```

The above functions should be familiar from the FMI spec. As you can see from the code, they have no implementation and you may override them in your own subclass. Only do_step is required, but you may also implement the others. What you do inside them is up to you, including calling other functions.
