### ISSUE TITLE
Problem with initialization

### ISSUE THREAD

**Issue by MinsGoing** [NTNU-IHB/PythonFMU#209]
![image](https://github.com/NTNU-IHB/PythonFMU/assets/37976972/58f0809b-a1df-4432-99c9-730857e24030)
![image](https://github.com/NTNU-IHB/PythonFMU/assets/37976972/20c59f5b-dee6-4bf6-a56e-e33378c25d23)
When I generate FMU and execute FMU, the initialized output is incorrect. The correct output should be as shown in the following image.
![image](https://github.com/NTNU-IHB/PythonFMU/assets/37976972/76f59ddc-be52-438e-8312-41793170ad5d)

**Comment by MinsGoing** [comment]
How to not assign initial values to input variables？

**Comment by markaren** [comment]
Are you sure the issue is not the importing tools' initialization? How about FMUs from other tools?

**Comment by MinsGoing** [comment]
> Are you sure the issue is not the importing tools' initialization? How about FMUs from other tools?

The fmu generated by the modelica is correct. The possible reason is that the modelica parameter can only be defined without assignment.
