### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by StephenSmith25** [NTNU-IHB/PythonFMU#218]
Hey,

I see a fix went in related to multiple initialization: e.g https://github.com/NTNU-IHB/PythonFMU/pull/213. Could you bump the version to include these changes?

Thanks,

Stephen

**Comment by markaren** [comment]
I will consider releasing a new version in the near future. But as I remember #213 is a fix for #211 and not any current issues.

**Comment by StephenSmith25** [comment]
Ah okay, no problem. I was just getting a similar error with the pypi installed version but I didn't read into it enough. I can close this for now then.
