### ISSUE TITLE
Binaries are no longer in the expected location in the resources directory structure

### ISSUE THREAD

**Issue by pamagister** [NTNU-IHB/PythonFMU#219]
The binaries (e.g. the pythonfmu-export.dll) were located at the following location up to version 0.6.3 (using win64 as an example):
`\pythonfmu\resources\binaries\win64\`
--> refer to https://files.pythonhosted.org/packages/31/b8/e976a7c2f8c856b63b1f17af4ceaf94b6bbf90ec57bac688f0a25c2a86ad/pythonfmu-0.6.3.tar.gz

The filing structure has been changed in version 0.6.4:
`\pythonfmu\resources\lib-wrapper-windows-2019\binaries\win64\`
--> refer to https://files.pythonhosted.org/packages/88/ca/7c56985806bbc4bc8becc69df234bc2d8cf17f0bb1fe2642db5e31ca1ac1/pythonfmu-0.6.4.tar.gz

As a result, the following error is caused when using pythonfmu-lib:
`ValueError: FmuBuilder binary is missing`

This change may have been caused by the following commit:
https://github.com/NTNU-IHB/PythonFMU/commit/e12ac4731869f3062866e9646cfdfb658b4dcd90

**Comment by markaren** [comment]
Yes, this is an issue that we are aware of and a hotfix will be published.

**Comment by Jorgelmh** [comment]
Just fixed the issue, will be releasing a fix within the hour, apologies for the trouble.

**Comment by Jorgelmh** [comment]
Issue is fixed! Please install newest version 0.6.5, let us know if you still face issues!

**Comment by pamagister** [comment]
I can confirm that the problem has been resolved, it does not occur anymore. Thanks a lot for the quick fix.
