### ISSUE TITLE
Binaries are not bundled when building locally

### ISSUE THREAD

**Issue by markaren** [NTNU-IHB/PythonFMU#27]
@fcollonval Your expertise is required here.
When I do `pip install .` followed by `pythonfmu-builder -f path/to/slave.py` the produced FMU does not contain binaries for the current platform. I can't run the integration tests either due to this. What gives? Why does it work in the CI? Intended behavior?

**Comment by markaren** [comment]
Ok, I see that the C does 
```
-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE="$Env:github_workspace/pythonfmu/resources/binaries/win64"
```
Any reason we should not hardcode this into CMakeLists.txt and add the output folder to .gitignore?

**Comment by fcollonval** [comment]
Usually I don't like to hard code the output directory. But in this precise case, the goal is not to use the library directly but just to include it into the FMU. So let's do as you propose. 

Note: the cmake option is different depending on the OS.

```
-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE="$Env:github_workspace/pythonfmu/resources/binaries/win64"

-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=$GITHUB_WORKSPACE/pythonfmu/resources/binaries/linux64          
```
