### ISSUE TITLE
Pass the visible flag to Python

### ISSUE THREAD

**Issue by fcollonval** [NTNU-IHB/PythonFMU#34]
FMI defines a instantiation option visible.
For completeness, we should pass it to the Python slave.

**Comment by markaren** [comment]
With additional ctro arguments, perhaps we should use `**kwargs` or something like that?

**Comment by fcollonval** [comment]
Yeah, that sounds like a possibility. But I must admit I have no clue how to create keyword Python args from the C++.
This project has really enhanced my knowledge on Python C/API.

**Comment by markaren** [comment]
We could probably use an argument list as well. The important part is to
a) make it extensible (add more arguments later w/o breaking clients
b) make it easier for end-users (one args vs many)

**Comment by fcollonval** [comment]
For a in-house code, we have a nice pattern using a hook method to be overwritten by the daughter class. So we can modify the instantiation without fearing breaking the API. Something like that:

```python
class Fmi2Slave(ABC):

    def __init__(self, *args, **kwargs):
        self.arg1 = arg1
        ...
        self._register_variables()

    @abstractmethod
    def _register_variables(self):
        pass

class RealSlave(Fmi2Slave):

    def _register_variables(self):
        self.intOut = 1
        self.realOut = 3.0
        self.booleanVariable = True
        self.stringVariable = "Hello World!"
        self.register_variable(Integer("intOut", causality=Fmi2Causality.output))
        self.register_variable(Real("realOut", causality=Fmi2Causality.output))
        self.register_variable(Boolean("booleanVariable", causality=Fmi2Causality.local))
        self.register_variable(String("stringVariable", causality=Fmi2Causality.local))
```

**Comment by markaren** [comment]
Uhm, I wonder of this relate to the visibility flag and other FMI related flags ?
The `*args, **kwargs` is how it's implemented in #38

**Comment by fcollonval** [comment]
I wrote `*args` and `**kwargs` by laziness 😉 

But I usually find an explicit list more readable. Especially for `*args` that don't carry any kind of description.

Do you think #38 is sufficient?

**Comment by markaren** [comment]
Yes, I do :)
