### ISSUE TITLE
Rely on FMPy

### ISSUE THREAD

**Issue by fcollonval** [NTNU-IHB/PythonFMU#43]
[FMPy](https://github.com/CATIA-Systems/FMPy) is a strong code that already defines data class for all XML elements of FMI. Moreover it has support for XML validation.

It could be interesting to depend on it to simplify and speed-up development here.

But this probably means to fix the segmentation fault raised when using Python exported FMUs with FMPy 😞

**Comment by markaren** [comment]
I'm all for it. However, as you say fixing the segfault probably means implementing #36, which is a major undertaking that will make the native part of the code much more complex. I assume.

**Comment by fcollonval** [comment]
Yep, that is my assumption too...

**Comment by markaren** [comment]
Wait a second, I thought you meant rely on FMPy for tests etc, not as an actual dependency. I rather not do that and keep things simple. For XML validation etc. we could run it though a XML schema validator like JAXB, which is available on JDK 1.8 systems. Or we could make tests running through the FMU Compliance Checker.

**Comment by fcollonval** [comment]
Thanks for point it out the [FMU Compliance Checker](https://github.com/modelica-tools/FMUComplianceChecker). I did not know about it.

To keep things simple, then I'll close this one.
