### ISSUE TITLE
The current platform (win64) is not supported by the FMU

### ISSUE THREAD

**Issue by FlorianKarg** [NTNU-IHB/PythonFMU#63]
Testing the FMU with FMPy gave me the following error:

![Unbenannt](https://user-images.githubusercontent.com/59643710/74643901-c5379880-5175-11ea-869d-0e05023d2c12.JPG)

I used the following Script: 
https://github.com/NTNU-IHB/PythonFMU/blob/master/pythonfmu/tests/pythonslave.py

**Comment by markaren** [comment]
FMPy won't work at this time. However this issue is unrelated to that. 
If you do `pip install .`, you'll need to build the binaries yourself.
Are you using `pip install pythonfmu` ? Are the binaries folder inside the FMU empty?

**Comment by FlorianKarg** [comment]
I'm using `python -m pip install pythonfmu --user` in the cmd prompt and I don't have a binaries folder inside the FMU.

**Comment by markaren** [comment]
That's weird. I just uninstalled the development version and installed using `pip install pythonfmu` (v.0.3.0). The generated FMU has linux64 and win64 binaires

**Comment by FlorianKarg** [comment]
That's weird. I just delated the package and reinstalled it and now there are binaries

**Comment by fcollonval** [comment]
@FlorianKarg `pip` is using a local cache. That may be the reason of that weird behavior.

**Comment by FlorianKarg** [comment]
@fcollonval 
Could this also be the reason for the following error? 

`C:\Users\karg\Desktop>pythonfmu-builder -f Test.py pythonfmu
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 193, in _run_module_as_ma
n
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\karg\AppData\Roaming\Python\Python38\Scripts\pythonfmu-builder
exe\__main__.py", line 7, in <module>
  File "C:\Users\karg\AppData\Roaming\Python\Python38\site-packages\pythonfmu\b
ilder.py", line 234, in main
    FmuBuilder.build_FMU(**options)
  File "C:\Users\karg\AppData\Roaming\Python\Python38\site-packages\pythonfmu\b
ilder.py", line 120, in build_FMU
    model_identifier, xml = ModelDescriptionFetcher.get_model_description(
  File "C:\Users\karg\AppData\Roaming\Python\Python38\site-packages\pythonfmu\b
ilder.py", line 53, in get_model_description
    instance = getattr(fmu_interface, class_name)("dummyInstance")
TypeError: __init__() takes 1 positional argument but 2 were given`
