### ISSUE TITLE
GIL not released when throwing an error

### ISSUE THREAD

**Issue by fcollonval** [NTNU-IHB/PythonFMU#68]
When an error is raised in Python and is captured by the `handle_py_exception`, a C++ error is raised before releasing the GIL => deadlock follows.

https://github.com/NTNU-IHB/PythonFMU/blob/6c9daafc3fe0163e3031705bcf62cc15c6b3b041/pythonfmu/pythonfmu-export/headers/pythonfmu/PyException.hpp#L40

@markaren what would be the best coding logic to fix this? Currently the PySlaveInstance methods are not aware of the `gil_state` due to the lambda usage.

Should we pass the `gil_state` to the lambda to be able to pass it to `handle_py_exception`? Or could we somehow encapsulate the `handle_py_exception` call so that it receives the `gil_state`?

**Comment by markaren** [comment]
We could pass `state` to the `instance` and call `state->handle_py_exception`. Probably

**Comment by markaren** [comment]
No, let's just pass the gilstate though the lambda.

**Comment by markaren** [comment]
```cpp
inline void py_safe_run(const std::function<void(PyGILState_STATE gil_state)>& f)
{
    PyGILState_STATE gil_state = PyGILState_Ensure();
    f(gil_state);
    PyGILState_Release(gil_state);
}
```

**Comment by markaren** [comment]
We should probably also decref members of ìnstance` when throwing the exception.

**Comment by fcollonval** [comment]
Thanks for the hints, I'll propose a fix.
