### ISSUE TITLE
__init__() got an unexpected keyword argument 'resources'

### ISSUE THREAD

**Issue by FlorianKarg** [NTNU-IHB/PythonFMU#72]
I tried to test my FMU with _FMUComplianceChecker_ and with _FMPy_ and there appears the following error:

`Fatal py exception encountered: [initialize] PyObject_Call
"__init__() got an unexpected keyword argument 'resources'"`

**Comment by markaren** [comment]
Can you paste your Constructor and super arguments?

**Comment by FlorianKarg** [comment]
I used the pythonslave.py example as well. I got the same error..

**Comment by markaren** [comment]
I do not get any errors with neither FMPy nor the compliance checker..

**Comment by markaren** [comment]
Are you sure you are running `v.0.4.0` ?

**Comment by FlorianKarg** [comment]
I was running the `v0.4.0` but used the wrong optional folder containing additional project files..
