### ISSUE TITLE
Bundle pythonfmu in FMU

### ISSUE THREAD

**Issue by markaren** [NTNU-IHB/PythonFMU#77]
I did not realize this until now, but pythonfmu is required to be installed on the target system unless `pythonfmu` is passed as an optional resource. However, this will include pretty much the entire `pythonfmu` project in the FMU (about 5MB of excess files), while we only need the top level pythonfmu files. I reckon pythonfmu should **always** be bundled with the FMU. 

@fcollonval thoughts?

**Comment by fcollonval** [comment]
@markaren This is a good idea. It will definitely ease the usage for Python FMU relying solely on built-in libraries.

Regarding the extra size, your PR is really good as copying only the Python files keep it light without breaking functionality.

> Note: The additional optimization could be to drop the builder in the copied files. But this will bring a lot of troubles for skipping a not really big file.
