### ISSUE TITLE
Publish on pypi with Github action

### ISSUE THREAD

**Issue by fcollonval** [NTNU-IHB/PythonFMU#99]
@markaren 
To ease publication of a new version upon release, the GitHub action can be used: see [documentation](https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries). However you are the only one able to set this up as you need to set secrets on this project.

**Comment by markaren** [comment]
I've added a secret named `PYPI_PYTHONFMU_API_TOKEN`. You should be able to use that secret if you like to go forward with this.

**Comment by fcollonval** [comment]
I added the CI script that should trigger the publication upon release creation.

A draft release note for 0.6.0 is ready, [there](https://github.com/NTNU-IHB/PythonFMU/releases). If you do see any emergency issue. I propose to go ahead with a new release (I bumped the version number already) and test this.

**Comment by markaren** [comment]
Go ahead :)

**Comment by fcollonval** [comment]
The publication is failing due to a unauthorized error; see https://github.com/NTNU-IHB/PythonFMU/runs/543111764

Could you please try the command for uploading the package using the environment variables and the API token you created?

```
TWINE_USERNAME="__token__"
TWINE_PASSWORD="pypi-${{ secrets.PYPI_PYTHONFMU_API_TOKEN }}"
python setup.py sdist bdist_wheel
twine upload --verbose --disable-progress-bar dist/*
```

**Comment by markaren** [comment]
Getting the same error..

**Comment by markaren** [comment]
When I generated the pypi API token I copied the entire thing into the GitHub secrets thingy.

**Comment by markaren** [comment]
The token is project scoped if that matters.

**Comment by fcollonval** [comment]
Victory https://github.com/NTNU-IHB/PythonFMU/runs/544706462

The trick was that the prefix `pypi-` was already included in the token 😞

**Comment by fcollonval** [comment]
To give you the information, the publication is done when you publish a new release from the [release section](https://github.com/NTNU-IHB/PythonFMU/releases).
